export const posts = [
  {
    id: '1',
    user: { name: 'Iris_Fishes', avatar: '/sample/avatars/a1.jpg' },
    photo: '/sample/catches/bass1.jpg',
    location: 'Sippo Lake, OH',
    species: 'Largemouth Bass',
    weight: '2.4 lb',
    likes: 128,
    comments: 14,
    time: '2h',
  },
  {
    id: '2',
    user: { name: 'DelilahCasts', avatar: '/sample/avatars/a2.jpg' },
    photo: '/sample/catches/pike1.jpg',
    location: 'Nimisila Reservoir, OH',
    species: 'Northern Pike',
    weight: '8.2 lb',
    likes: 203,
    comments: 31,
    time: '5h',
  },
  {
    id: '3',
    user: { name: 'JazOnTheLake', avatar: '/sample/avatars/a3.jpg' },
    photo: '/sample/catches/bowfin1.jpg',
    location: 'Tuscarawas River, OH',
    species: 'Bowfin',
    weight: '6.7 lb',
    likes: 342,
    comments: 58,
    time: '1d',
  },
];
