export type RegulationDetails = {
  description: string;
  bagLimit: string;
  referenceUrl?: string;
};

export type FishingSpot = {
  id: string;
  name: string;
  state: string;
  waterbodyType: "Lake" | "Reservoir" | "River" | "Bay" | "Marsh" | "Backwater";
  latitude: number;
  longitude: number;
  publicAccess: boolean;
  accessNotes: string;
  species: string[];
  regulations: RegulationDetails | null;
  latestCatch: {
    species: string;
    weight: string;
    bait: string;
  } | null;
};

export const fishingSpotsUS: FishingSpot[] = [
  {
    id: "lake-of-the-woods",
    name: "Lake of the Woods",
    state: "MN",
    waterbodyType: "Lake",
    latitude: 49.195,
    longitude: -94.795,
    publicAccess: true,
    accessNotes: "Numerous public launches in Baudette and Wheelers Point; ice roads maintained in winter.",
    species: ["Walleye", "Sauger", "Northern Pike", "Yellow Perch"],
    regulations: {
      description: "Minnesota-Ontario border water regulations apply; special winter harvest slots.",
      bagLimit: "Walleye/Sauger combined 6 (winter) or 4 (summer) with slot limits.",
      referenceUrl: "https://www.dnr.state.mn.us/fishing/index.html",
    },
    latestCatch: null,
  },
  {
    id: "lake-okeechobee",
    name: "Lake Okeechobee",
    state: "FL",
    waterbodyType: "Lake",
    latitude: 26.948,
    longitude: -80.796,
    publicAccess: true,
    accessNotes: "Large levee encircles lake; major ramps at Clewiston, Belle Glade, and Okeechobee City.",
    species: ["Largemouth Bass", "Black Crappie", "Bluegill", "Sunshine Bass"],
    regulations: {
      description: "Florida statewide freshwater regulations with special trophy bass rules.",
      bagLimit: "Bass 5 (only one over 16\"), Crappie 25.",
      referenceUrl: "https://myfwc.com/fishing/freshwater/",
    },
    latestCatch: {
      species: "Largemouth Bass",
      weight: "7.6 lb",
      bait: "Wild shiner",
    },
  },
  {
    id: "lake-guntersville",
    name: "Lake Guntersville",
    state: "AL",
    waterbodyType: "Reservoir",
    latitude: 34.410,
    longitude: -86.293,
    publicAccess: true,
    accessNotes: "Public ramps at Guntersville State Park and multiple TVA access areas; shoreline parks maintained by municipalities.",
    species: ["Largemouth Bass", "Smallmouth Bass", "Crappie", "Catfish"],
    regulations: {
      description: "Tennessee River impoundment regulations; check grass mat closures for waterfowl areas.",
      bagLimit: "Black bass 10 (≥ 15\" for largemouth), Crappie 30.",
      referenceUrl: "https://www.outdooralabama.com/fishing/freshwater-fishing",
    },
    latestCatch: null,
  },
  {
    id: "lake-mead",
    name: "Lake Mead",
    state: "NV/AZ",
    waterbodyType: "Reservoir",
    latitude: 36.015,
    longitude: -114.737,
    publicAccess: true,
    accessNotes: "Launch ramps at Hemenway Harbor, Callville Bay, and Temple Bar within Lake Mead National Recreation Area; entry fees apply.",
    species: ["Striped Bass", "Largemouth Bass", "Channel Catfish", "Rainbow Trout"],
    regulations: {
      description: "Nevada/Arizona reciprocal fishing agreement; National Park Service boating rules in effect.",
      bagLimit: "Striped bass 20 (no size limit), Black bass 6 (≥ 13\").",
      referenceUrl: "https://www.nps.gov/lake/learn/nature/fishing.htm",
    },
    latestCatch: null,
  },
  {
    id: "lake-powell",
    name: "Lake Powell",
    state: "UT/AZ",
    waterbodyType: "Reservoir",
    latitude: 37.040,
    longitude: -111.373,
    publicAccess: true,
    accessNotes: "Wahweap, Antelope Point, and Bullfrog marinas offer paved ramps; permit required for Glen Canyon National Recreation Area entry.",
    species: ["Striped Bass", "Smallmouth Bass", "Walleye", "Crappie"],
    regulations: {
      description: "Utah and Arizona licenses both honored; encourage harvest of striped bass to maintain forage balance.",
      bagLimit: "Striped bass no limit, Smallmouth bass 20.",
      referenceUrl: "https://www.nps.gov/glca/planyourvisit/fishing.htm",
    },
    latestCatch: null,
  },
  {
    id: "lake-champlain",
    name: "Lake Champlain",
    state: "NY/VT",
    waterbodyType: "Lake",
    latitude: 44.500,
    longitude: -73.300,
    publicAccess: true,
    accessNotes: "State launches at Plattsburgh, Burlington, and Addison County; ferry crossings provide additional access points.",
    species: ["Lake Trout", "Landlocked Salmon", "Smallmouth Bass", "Northern Pike"],
    regulations: {
      description: "Bilateral New York/Vermont management zone; special seasons for trout and salmon.",
      bagLimit: "Lake trout 2 (≥ 18\"), Salmon 2 (≥ 15\").",
      referenceUrl: "https://dec.vermont.gov/fish/angler-resources/lake-champlain",
    },
    latestCatch: null,
  },
  {
    id: "lake-erie-western-basin",
    name: "Lake Erie Western Basin",
    state: "OH/MI",
    waterbodyType: "Lake",
    latitude: 41.700,
    longitude: -82.800,
    publicAccess: true,
    accessNotes: "Public marinas at Port Clinton, Catawba Island, and Detroit River mouth; numerous charter services.",
    species: ["Walleye", "Yellow Perch", "Smallmouth Bass", "Sheepshead"],
    regulations: {
      description: "Seasonal walleye bag limits set monthly by Ohio DNR; check border waters agreement with Michigan.",
      bagLimit: "Walleye 6 (Mar–Apr 4), Yellow perch 30.",
      referenceUrl: "https://ohiodnr.gov/",
    },
    latestCatch: null,
  },
  {
    id: "lake-washington",
    name: "Lake Washington",
    state: "WA",
    waterbodyType: "Lake",
    latitude: 47.620,
    longitude: -122.250,
    publicAccess: true,
    accessNotes: "Urban launches at Magnuson Park, Gene Coulon Memorial Beach, and Leschi; limited parking on weekends.",
    species: ["Cutthroat Trout", "Smallmouth Bass", "Yellow Perch", "Coho Salmon"],
    regulations: {
      description: "Washington statewide lake rules with selective gear periods for trout.",
      bagLimit: "Trout 2 (≥ 12\"), Bass 5 (only 1 over 17\").",
      referenceUrl: "https://wdfw.wa.gov/fishing/",
    },
    latestCatch: null,
  },
  {
    id: "clear-lake-ca",
    name: "Clear Lake",
    state: "CA",
    waterbodyType: "Lake",
    latitude: 39.020,
    longitude: -122.770,
    publicAccess: true,
    accessNotes: "County-maintained ramps at Redbud Park, Library Park, and Lucerne; inspection for quagga mussels required.",
    species: ["Largemouth Bass", "Crappie", "Bluegill", "Channel Catfish"],
    regulations: {
      description: "California freshwater rules; local invasive species sticker mandatory.",
      bagLimit: "Black bass 5 (≥ 12\"), Crappie 25.",
      referenceUrl: "https://wildlife.ca.gov/Fishing",
    },
    latestCatch: {
      species: "Largemouth Bass",
      weight: "8.1 lb",
      bait: "Brown jig",
    },
  },
  {
    id: "lake-fork",
    name: "Lake Fork Reservoir",
    state: "TX",
    waterbodyType: "Reservoir",
    latitude: 32.808,
    longitude: -95.635,
    publicAccess: true,
    accessNotes: "Sabine River Authority parks provide ramps; trophy bass slot monitored with voluntary catch reporting kiosks.",
    species: ["Largemouth Bass", "Crappie", "Sunfish", "Channel Catfish"],
    regulations: {
      description: "Special 16-24\" slot for largemouth bass; ShareLunker program encourages release of trophies.",
      bagLimit: "Bass 5 (under 16\" or over 24\" only), Crappie 25.",
      referenceUrl: "https://tpwd.texas.gov/fishboat/fish/",
    },
    latestCatch: null,
  },
  {
    id: "sam-rayburn",
    name: "Sam Rayburn Reservoir",
    state: "TX",
    waterbodyType: "Reservoir",
    latitude: 31.079,
    longitude: -94.043,
    publicAccess: true,
    accessNotes: "USACE facilities with multiple ramps and campgrounds; Angelina National Forest shoreline accessible.",
    species: ["Largemouth Bass", "Crappie", "Catfish", "White Bass"],
    regulations: {
      description: "East Texas reservoir regulations; occasional hydrilla treatments noted by TPWD.",
      bagLimit: "Black bass 5 (≥ 14\"), White bass 25.",
      referenceUrl: "https://tpwd.texas.gov/fishboat/fish/",
    },
    latestCatch: null,
  },
  {
    id: "lake-marion",
    name: "Lake Marion (Santee Cooper)",
    state: "SC",
    waterbodyType: "Reservoir",
    latitude: 33.520,
    longitude: -80.490,
    publicAccess: true,
    accessNotes: "Santee Cooper public ramps, state parks, and fish camps line the shoreline; stump-filled flats require navigation caution.",
    species: ["Blue Catfish", "Crappie", "Striped Bass", "Largemouth Bass"],
    regulations: {
      description: "Santee Cooper system catfish trophy limit and striped bass seasonal closures.",
      bagLimit: "Blue catfish 25 (only 1 over 32\"), Striped bass 3 in open season.",
      referenceUrl: "https://www.dnr.sc.gov/fishing.html",
    },
    latestCatch: null,
  },
  {
    id: "lake-st-clair",
    name: "Lake St. Clair",
    state: "MI/ON",
    waterbodyType: "Lake",
    latitude: 42.468,
    longitude: -82.728,
    publicAccess: true,
    accessNotes: "Metropark launches, 9 Mile boat launch, and St. Clair Shores marinas provide ample access; heavy summer boat traffic.",
    species: ["Smallmouth Bass", "Muskellunge", "Yellow Perch", "Walleye"],
    regulations: {
      description: "Great Lakes regulations with cross-border considerations; muskie catch-and-release season dates vary.",
      bagLimit: "Smallmouth bass 5 (≥ 14\"), Muskie catch-and-release only except during open harvest season.",
      referenceUrl: "https://www.michigan.gov/dnr/things-to-do/fishing",
    },
    latestCatch: null,
  },
  {
    id: "lake-havasu",
    name: "Lake Havasu",
    state: "AZ/CA",
    waterbodyType: "Reservoir",
    latitude: 34.434,
    longitude: -114.352,
    publicAccess: true,
    accessNotes: "Ramps at Lake Havasu State Park, Windsor Beach, and Site Six; shoreline fishing piers maintained by Bureau of Land Management.",
    species: ["Striped Bass", "Smallmouth Bass", "Redear Sunfish", "Channel Catfish"],
    regulations: {
      description: "Colorado River special regulations; Arizona and California licenses honored reciprocally.",
      bagLimit: "Striped bass 10, Redear sunfish 25.",
      referenceUrl: "https://azgfd.com/fishing/",
    },
    latestCatch: {
      species: "Redear Sunfish",
      weight: "2.1 lb",
      bait: "Nightcrawler",
    },
  },
  {
    id: "percy-priest",
    name: "J. Percy Priest Lake",
    state: "TN",
    waterbodyType: "Reservoir",
    latitude: 36.095,
    longitude: -86.571,
    publicAccess: true,
    accessNotes: "U.S. Army Corps of Engineers maintains over a dozen ramps; Nashville shoreline parks provide bank access.",
    species: ["Striped Bass", "Crappie", "Largemouth Bass", "Sauger"],
    regulations: {
      description: "Cumberland River impoundment rules; restricted zones near dam and water intake structures.",
      bagLimit: "Striped bass 2 (≥ 15\"), Crappie 15 (≥ 10\").",
      referenceUrl: "https://www.tn.gov/twra/fishing.html",
    },
    latestCatch: null,
  },
  {
    id: "lake-winnipesaukee",
    name: "Lake Winnipesaukee",
    state: "NH",
    waterbodyType: "Lake",
    latitude: 43.646,
    longitude: -71.365,
    publicAccess: true,
    accessNotes: "Public ramps at Weirs Beach, Wolfeboro, and Meredith; winter access via snowmobile routes.",
    species: ["Lake Trout", "Landlocked Salmon", "Smallmouth Bass", "White Perch"],
    regulations: {
      description: "New Hampshire designated trout lake with seasonal salmon trolling restrictions.",
      bagLimit: "Lake trout 2 (≥ 18\"), Salmon 1 (≥ 15\").",
      referenceUrl: "https://www.wildlife.state.nh.us/fishing/",
    },
    latestCatch: null,
  },
  {
    id: "lake-lanier",
    name: "Lake Lanier",
    state: "GA",
    waterbodyType: "Reservoir",
    latitude: 34.238,
    longitude: -83.933,
    publicAccess: true,
    accessNotes: "Corps of Engineers parks with ramps; night fishing piers at Lower Overlook and West Bank Park.",
    species: ["Spotted Bass", "Striped Bass", "Crappie", "Bluegill"],
    regulations: {
      description: "Chattahoochee River reservoir rules; blueback herring bait regulations enforced.",
      bagLimit: "Black bass 10 (Spotted bass no size limit), Striped bass 2 (≥ 22\").",
      referenceUrl: "https://georgiawildlife.com/fishing",
    },
    latestCatch: null,
  },
  {
    id: "caddo-lake",
    name: "Caddo Lake",
    state: "TX/LA",
    waterbodyType: "Lake",
    latitude: 32.681,
    longitude: -94.083,
    publicAccess: true,
    accessNotes: "Caddo Lake State Park, Mooringsport ramp, and Oil City provide access; maze of cypress channels favors shallow-draft boats.",
    species: ["Largemouth Bass", "Crappie", "Blue Catfish", "Chain Pickerel"],
    regulations: {
      description: "Border water regulations shared by Texas and Louisiana; aquatic vegetation control zones posted.",
      bagLimit: "Bass 8 (≥ 14\"), Catfish 50 combined.",
      referenceUrl: "https://tpwd.texas.gov/fishboat/fish/",
    },
    latestCatch: null,
  },
  {
    id: "flaming-gorge",
    name: "Flaming Gorge Reservoir",
    state: "UT/WY",
    waterbodyType: "Reservoir",
    latitude: 40.912,
    longitude: -109.423,
    publicAccess: true,
    accessNotes: "Lucerne Valley, Buckboard, and Cedar Springs marinas with deep-water ramps; high elevation requires cold-weather prep.",
    species: ["Lake Trout", "Kokanee Salmon", "Smallmouth Bass", "Burbot"],
    regulations: {
      description: "Reciprocal permit for Utah and Wyoming sections; burbot removal encouraged.",
      bagLimit: "Lake trout 12 (only 1 over 28\"), Kokanee 3.",
      referenceUrl: "https://wildlife.utah.gov/",
    },
    latestCatch: null,
  },
  {
    id: "mille-lacs",
    name: "Mille Lacs Lake",
    state: "MN",
    waterbodyType: "Lake",
    latitude: 46.200,
    longitude: -93.700,
    publicAccess: true,
    accessNotes: "State-owned launches at Garrison, Father Hennepin State Park, and Isle; ice road network in winter.",
    species: ["Smallmouth Bass", "Walleye", "Northern Pike", "Tullibee"],
    regulations: {
      description: "Frequent mid-season adjustments to walleye harvest; check slot sizes before retaining fish.",
      bagLimit: "Smallmouth catch-and-release most of year; walleye seasons vary by proclamation.",
      referenceUrl: "https://www.dnr.state.mn.us/fishing/millelacs.html",
    },
    latestCatch: null,
  },
  {
    id: "grand-lake",
    name: "Grand Lake o' the Cherokees",
    state: "OK",
    waterbodyType: "Reservoir",
    latitude: 36.573,
    longitude: -94.849,
    publicAccess: true,
    accessNotes: "Grand River Dam Authority parks with ramps; Pensacola Dam tailrace offers shoreline fishing platforms.",
    species: ["White Bass", "Crappie", "Blue Catfish", "Largemouth Bass"],
    regulations: {
      description: "Oklahoma statewide rules with paddlefish permit requirements nearby.",
      bagLimit: "Black bass 6 (≥ 14\"), Catfish 15 combined.",
      referenceUrl: "https://wildlifedepartment.com/fishing",
    },
    latestCatch: null,
  },
  {
    id: "lake-tahoe",
    name: "Lake Tahoe",
    state: "CA/NV",
    waterbodyType: "Lake",
    latitude: 39.096,
    longitude: -120.032,
    publicAccess: true,
    accessNotes: "State parks and marinas at South Lake Tahoe, Tahoe City, and Sand Harbor; clear water demands long leaders for trout trolling.",
    species: ["Mackinaw Trout", "Rainbow Trout", "Kokanee Salmon", "Smallmouth Bass"],
    regulations: {
      description: "California/Nevada reciprocal waters; check tributary closures for spawning kokanee.",
      bagLimit: "Trout/Kokanee 5 (no more than 2 mackinaw).",
      referenceUrl: "https://wildlife.ca.gov/Fishing/Inland/Lake-Tahoe",
    },
    latestCatch: null,
  },
  {
    id: "lake-hartwell",
    name: "Lake Hartwell",
    state: "GA/SC",
    waterbodyType: "Reservoir",
    latitude: 34.423,
    longitude: -82.874,
    publicAccess: true,
    accessNotes: "Corps campgrounds and ramps throughout; Clemson’s Twelve Mile Recreation Area popular for bank anglers.",
    species: ["Striped Bass", "Hybrid Bass", "Crappie", "Blue Catfish"],
    regulations: {
      description: "Reciprocal Georgia/South Carolina agreement; blueback herring bait transport rules enforced.",
      bagLimit: "Striped/hybrid bass 10 (≥ 12\"), Crappie 30.",
      referenceUrl: "https://www.dnr.sc.gov/fishing.html",
    },
    latestCatch: null,
  },
  {
    id: "lake-ouachita",
    name: "Lake Ouachita",
    state: "AR",
    waterbodyType: "Reservoir",
    latitude: 34.606,
    longitude: -93.239,
    publicAccess: true,
    accessNotes: "Ouachita National Forest shoreline largely undeveloped; marinas at Crystal Springs, Mountain Harbor, and Brady Mountain.",
    species: ["Striped Bass", "Largemouth Bass", "Spotted Bass", "Bream"],
    regulations: {
      description: "Clean, clear water managed by Arkansas Game and Fish; zebra mussel decontamination stations present.",
      bagLimit: "Striped bass 6, Black bass 10 combined.",
      referenceUrl: "https://www.agfc.com/en/fishing/",
    },
    latestCatch: null,
  },
  {
    id: "elephant-butte",
    name: "Elephant Butte Reservoir",
    state: "NM",
    waterbodyType: "Reservoir",
    latitude: 33.181,
    longitude: -107.189,
    publicAccess: true,
    accessNotes: "Elephant Butte Lake State Park provides marinas, primitive launches, and beach driving access when water levels allow.",
    species: ["White Bass", "Striped Bass", "Channel Catfish", "Bluegill"],
    regulations: {
      description: "New Mexico State Park regulations; dry conditions may limit ramp hours.",
      bagLimit: "Striped bass 1 (≥ 35\"), White bass 25.",
      referenceUrl: "https://www.wildlife.state.nm.us/fishing/",
    },
    latestCatch: null,
  },
  {
    id: "shasta-lake",
    name: "Shasta Lake",
    state: "CA",
    waterbodyType: "Reservoir",
    latitude: 40.741,
    longitude: -122.309,
    publicAccess: true,
    accessNotes: "Multiple marinas and public ramps under U.S. Forest Service; fluctuating water levels expose hazards.",
    species: ["Spotted Bass", "Rainbow Trout", "Kokanee Salmon", "Brown Trout"],
    regulations: {
      description: "California inland salmonid rules; barbless hooks required in certain tributaries.",
      bagLimit: "Trout/salmon 5 (no more than 2 brown trout).",
      referenceUrl: "https://wildlife.ca.gov/Fishing",
    },
    latestCatch: null,
  },
  {
    id: "lake-sakakawea",
    name: "Lake Sakakawea",
    state: "ND",
    waterbodyType: "Reservoir",
    latitude: 47.498,
    longitude: -101.308,
    publicAccess: true,
    accessNotes: "State parks at Fort Stevenson, Lake Sakakawea, and Lewis & Clark offer full-service marinas; wind can create large rollers.",
    species: ["Walleye", "Northern Pike", "Chinook Salmon", "Smallmouth Bass"],
    regulations: {
      description: "Missouri River system rules; darkhouse spearfishing allowed in winter with permit.",
      bagLimit: "Walleye/sauger 5 (possession 10), Pike 3.",
      referenceUrl: "https://gf.nd.gov/fishing",
    },
    latestCatch: null,
  },
  {
    id: "lake-texoma",
    name: "Lake Texoma",
    state: "TX/OK",
    waterbodyType: "Reservoir",
    latitude: 33.817,
    longitude: -96.571,
    publicAccess: true,
    accessNotes: "Highport, Catfish Bay, and Eisenhower State Park ramps provide deep-water access; striper guides common.",
    species: ["Striped Bass", "Blue Catfish", "Smallmouth Bass", "Crappie"],
    regulations: {
      description: "Requires Lake Texoma fishing license for full access to both states' waters.",
      bagLimit: "Striped bass 5 (only 2 over 20\"), Catfish 15 combined.",
      referenceUrl: "https://tpwd.texas.gov/fishboat/fish/",
    },
    latestCatch: null,
  },
  {
    id: "lake-cumberland",
    name: "Lake Cumberland",
    state: "KY",
    waterbodyType: "Reservoir",
    latitude: 36.940,
    longitude: -84.847,
    publicAccess: true,
    accessNotes: "State park marinas, Corps ramps, and Wolf Creek Dam tailwater access; steep banks require caution for shoreline anglers.",
    species: ["Striped Bass", "Smallmouth Bass", "Walleye", "Crappie"],
    regulations: {
      description: "Seasonal trout stockings below dam; striped bass managed with trophy regulations.",
      bagLimit: "Striped bass 2 (≥ 24\"), Trout 5 combined.",
      referenceUrl: "https://fw.ky.gov/Fish/Pages/default.aspx",
    },
    latestCatch: null,
  },
  {
    id: "blue-mesa",
    name: "Blue Mesa Reservoir",
    state: "CO",
    waterbodyType: "Reservoir",
    latitude: 38.486,
    longitude: -107.306,
    publicAccess: true,
    accessNotes: "Curecanti National Recreation Area maintains Elk Creek, Lake Fork, and Stevens Creek ramps; summer inspection for invasive mussels required.",
    species: ["Lake Trout", "Kokanee Salmon", "Brown Trout", "Rainbow Trout"],
    regulations: {
      description: "Colorado Parks and Wildlife encourages harvest of small lake trout; snagging kokanee allowed in fall at designated areas.",
      bagLimit: "Lake trout unlimited under 24\", only 1 over 32\"; Kokanee 5 except during snagging season.",
      referenceUrl: "https://cpw.state.co.us/thingstodo/Pages/Fishing.aspx",
    },
    latestCatch: null,
  },
  {
    id: "columbia-river-hanford-reach",
    name: "Columbia River Hanford Reach",
    state: "WA",
    waterbodyType: "River",
    latitude: 46.625,
    longitude: -119.573,
    publicAccess: true,
    accessNotes:
      "Shoreline access at Vernita Bridge and Ringold Springs; jet boats launch from Columbia Point and White Bluffs ramps.",
    species: ["Chinook Salmon", "Steelhead", "Smallmouth Bass", "Sturgeon"],
    regulations: {
      description: "Selective gear rules during salmon seasons; barbless hooks and catch record card required for sturgeon.",
      bagLimit: "Fall Chinook 6 (only 1 adult), Sturgeon catch-and-release only except within designated retention dates.",
      referenceUrl: "https://wdfw.wa.gov/fishing/regulations",
    },
    latestCatch: null,
  },
  {
    id: "mississippi-river-pool-4",
    name: "Mississippi River Pool 4",
    state: "MN/WI",
    waterbodyType: "River",
    latitude: 44.444,
    longitude: -92.116,
    publicAccess: true,
    accessNotes:
      "Public ramps at Bay Point Park (Red Wing), Everts Resort, and Alma Marina; wing dams and current seams popular for jigging.",
    species: ["Walleye", "Sauger", "Channel Catfish", "White Bass"],
    regulations: {
      description: "Border water regulations shared by Minnesota and Wisconsin; winter closure below Lock & Dam 3 for waterfowl sanctuary.",
      bagLimit: "Walleye/sauger combined 6 (only 1 over 20\"), Catfish 10 combined.",
      referenceUrl: "https://www.dnr.state.mn.us/fishing/index.html",
    },
    latestCatch: null,
  },
  {
    id: "delaware-river-tidal",
    name: "Delaware River Tidal Reach",
    state: "PA/NJ/DE",
    waterbodyType: "River",
    latitude: 39.872,
    longitude: -75.130,
    publicAccess: true,
    accessNotes:
      "Boat launches at Tacony, Gloucester City, and Delaware City; urban piers provide bank access with tidal current awareness.",
    species: ["Striped Bass", "American Shad", "Channel Catfish", "White Perch"],
    regulations: {
      description: "Slot-size management for striped bass; check state-specific seasons for shad and herring closures.",
      bagLimit: "Striped bass 1 (28-31\" slot in NJ/DE, 28-35\" in PA), Shad catch-and-release in conservation zones.",
      referenceUrl: "https://www.nj.gov/dep/fgw/pdf/2024/maregsum.pdf",
    },
    latestCatch: null,
  },
  {
    id: "susquehanna-river-north-branch",
    name: "Susquehanna River North Branch",
    state: "PA",
    waterbodyType: "River",
    latitude: 41.245,
    longitude: -76.002,
    publicAccess: true,
    accessNotes:
      "PFBC access areas at Bloomsburg, Tunkhannock, and Falls; kayak-friendly riffles with smallmouth habitat.",
    species: ["Smallmouth Bass", "Walleye", "Flathead Catfish", "Muskellunge"],
    regulations: {
      description: "Catch-and-release only for bass during spring spawn; invasive flathead catfish removal encouraged.",
      bagLimit: "Smallmouth bass closed season Apr 1-Jun 10; Walleye 6 (≥ 15\").",
      referenceUrl: "https://www.fishandboat.com/Regulations/Pages/default.aspx",
    },
    latestCatch: null,
  },
  {
    id: "chesapeake-bay-mid",
    name: "Chesapeake Bay Mid-Bay",
    state: "MD/VA",
    waterbodyType: "Bay",
    latitude: 38.693,
    longitude: -76.260,
    publicAccess: true,
    accessNotes:
      "Public ramps at Sandy Point, Matapeake, and Windmill Point; wide open water favors larger vessels and weather monitoring.",
    species: ["Striped Bass", "Bluefish", "Red Drum", "Cobia"],
    regulations: {
      description: "Seasonal striped bass harvest windows; circle hooks required when fishing natural bait for striped bass.",
      bagLimit: "Striped bass 1 (19-24\" spring trophy exceptions), Red drum 3 (18-27\" in VA).",
      referenceUrl: "https://dwr.virginia.gov/fishing/regulations/",
    },
    latestCatch: null,
  },
  {
    id: "kenai-river-middle",
    name: "Kenai River Middle Run",
    state: "AK",
    waterbodyType: "River",
    latitude: 60.524,
    longitude: -150.879,
    publicAccess: true,
    accessNotes:
      "State-managed launches at Soldotna, Swiftwater, and Moose Range Meadows; boardwalks protect riverbanks for walk-in anglers.",
    species: ["King Salmon", "Sockeye Salmon", "Rainbow Trout", "Dolly Varden"],
    regulations: {
      description: "Frequent emergency orders adjust king salmon harvest; single-hook, no-bait restrictions in trophy trout zones.",
      bagLimit: "King salmon 1 per day when open (annual limit 2-5 by area), Rainbow trout catch-and-release in trophy section.",
      referenceUrl: "https://www.adfg.alaska.gov/index.cfm?adfg=fishingSportFishMain.main",
    },
    latestCatch: null,
  },
  {
    id: "lake-pontchartrain",
    name: "Lake Pontchartrain",
    state: "LA",
    waterbodyType: "Lake",
    latitude: 30.200,
    longitude: -90.100,
    publicAccess: true,
    accessNotes:
      "Ramps at Seabrook, Bonnabel, and Slidell; concrete fishing piers along Lakefront causeway provide shoreline options.",
    species: ["Speckled Trout", "Redfish", "Sheepshead", "Black Drum"],
    regulations: {
      description: "Louisiana coastal regulations with slot sizes for red drum and speckled trout adjustments during spring closures.",
      bagLimit: "Redfish 5 (16-27\"), Speckled trout 25 west zone / 15 east zone with size minimums.",
      referenceUrl: "https://www.wlf.louisiana.gov/page/recreational-saltwater-finfish",
    },
    latestCatch: null,
  },
  {
    id: "saginaw-bay",
    name: "Saginaw Bay",
    state: "MI",
    waterbodyType: "Bay",
    latitude: 43.800,
    longitude: -83.700,
    publicAccess: true,
    accessNotes:
      "Harbors at Linwood, Au Gres, and Bay City State Park; expansive flats require long runs to reach structure.",
    species: ["Walleye", "Yellow Perch", "Channel Catfish", "Lake Whitefish"],
    regulations: {
      description: "Great Lakes regulations; winter ice shanty registration required when ice forms.",
      bagLimit: "Walleye 8 (≥ 13\"), Yellow perch 25.",
      referenceUrl: "https://www.michigan.gov/dnr/things-to-do/fishing",
    },
    latestCatch: null,
  },
  {
    id: "lake-superior-apostle-islands",
    name: "Lake Superior Apostle Islands",
    state: "WI",
    waterbodyType: "Lake",
    latitude: 47.000,
    longitude: -90.700,
    publicAccess: true,
    accessNotes:
      "Marinas at Bayfield and Cornucopia; cold-water safety gear essential and weather can change rapidly around islands.",
    species: ["Lake Trout", "Coho Salmon", "Brown Trout", "Whitefish"],
    regulations: {
      description: "Lake Superior special regulations with seasonal lake trout quotas; barbless hook requirements in sanctuary zones.",
      bagLimit: "Lake trout 2-5 depending on zone, Brown trout 5 (≥ 10\").",
      referenceUrl: "https://dnr.wisconsin.gov/topic/Fishing/lakesuperior",
    },
    latestCatch: null,
  },
  {
    id: "everglades-flamingo",
    name: "Everglades Flamingo Backcountry",
    state: "FL",
    waterbodyType: "Backwater",
    latitude: 25.141,
    longitude: -80.922,
    publicAccess: true,
    accessNotes:
      "Launch from Flamingo Marina into shallow bays and mangrove creeks; shallow-draft skiffs and kayaks ideal for navigating poles-and-troll zones.",
    species: ["Snook", "Redfish", "Tarpon", "Sea Trout"],
    regulations: {
      description: "Everglades National Park permit required; special closures for manatee protection and pole-and-troll areas.",
      bagLimit: "Snook 1 (28-32\" Atlantic season), Redfish 1 (18-27\"), Tarpon catch-and-release except with harvest tag.",
      referenceUrl: "https://www.nps.gov/ever/planyourvisit/fishing.htm",
    },
    latestCatch: null,
  },
  {
    id: "san-juan-river-quality-waters",
    name: "San Juan River Quality Waters",
    state: "NM",
    waterbodyType: "River",
    latitude: 36.815,
    longitude: -107.637,
    publicAccess: true,
    accessNotes:
      "Below Navajo Dam with access at Texas Hole, Cottonwood Campground, and Lone Pine; wade fishing in clear tailwater.",
    species: ["Rainbow Trout", "Brown Trout"],
    regulations: {
      description: "Quality waters section requires barbless hooks and catch-and-release for trout.",
      bagLimit: "Catch-and-release only within quality waters; standard statewide limits outside.",
      referenceUrl: "https://www.wildlife.state.nm.us/fishing/river-surface-waters/",
    },
    latestCatch: null,
  },
  {
    id: "colorado-river-glenwood",
    name: "Colorado River Glenwood Canyon",
    state: "CO",
    waterbodyType: "River",
    latitude: 39.550,
    longitude: -107.333,
    publicAccess: true,
    accessNotes:
      "Public access via Bair Ranch, Grizzly Creek, and No Name rest area; float trips common during caddis hatches.",
    species: ["Rainbow Trout", "Brown Trout", "Mountain Whitefish"],
    regulations: {
      description: "Artificial flies and lures only from Shoshone to Hanging Lake; whirling disease-resistant trout stocked.",
      bagLimit: "Trout 4 statewide (only 2 ≥ 14\"), with local catch-and-release stretches.",
      referenceUrl: "https://cpw.state.co.us/thingstodo/Pages/Fishing.aspx",
    },
    latestCatch: null,
  },
  {
    id: "potomac-river-tidal",
    name: "Potomac River Tidal Basin",
    state: "DC/MD/VA",
    waterbodyType: "River",
    latitude: 38.871,
    longitude: -77.036,
    publicAccess: true,
    accessNotes:
      "Bank access at Hains Point, Gravelly Point, and National Harbor piers; tidal swings and urban navigation considerations.",
    species: ["Largemouth Bass", "Blue Catfish", "Snakehead", "Striped Bass"],
    regulations: {
      description: "DC fishing license honored in tidal Potomac with MD reciprocity; invasive northern snakehead harvest encouraged.",
      bagLimit: "Largemouth bass 5 (≥ 12\"), Blue catfish unlimited in many stretches, Snakehead must not be released alive.",
      referenceUrl: "https://dnr.maryland.gov/fisheries/Pages/index.aspx",
    },
    latestCatch: null,
  },
  {
    id: "lake-pepin",
    name: "Lake Pepin",
    state: "MN/WI",
    waterbodyType: "Lake",
    latitude: 44.408,
    longitude: -92.168,
    publicAccess: true,
    accessNotes:
      "Launches at Lake City, Pepin, and Stockholm; expansive main-lake requires wind awareness, backwater sloughs hold panfish.",
    species: ["Walleye", "Crappie", "Channel Catfish", "Northern Pike"],
    regulations: {
      description: "Managed as part of Mississippi River Pool 4 with joint Minnesota/Wisconsin regulations.",
      bagLimit: "Walleye/sauger combined 6 (only 1 over 20\"), Northern pike 3.",
      referenceUrl: "https://www.dnr.state.mn.us/fishing/index.html",
    },
    latestCatch: null,
  },
];
